return {
    {item = "ash", icon = nil, stage = 1, icon_size = 64},
    {item = "bonemeal", icon = nil, stage = 1, icon_size = 64},
    {item = "borax", icon = nil, stage = 1, icon_size = 64},
    {item = "boron-trioxide", icon = nil, stage = 1, icon_size = 64},
    {item = "calcium-carbide", icon = nil, stage = 1, icon_size = 64},
    {item = "chromium", icon = nil, stage = 1, icon_size = 64},
    {item = "chromite-sand", iconName = "chromite_sand", icon = nil, stage = 1, icon_size = 64},
    {item = "coal-dust", iconName = "coal_dust", icon = nil, stage = 1, icon_size = 64},
    {item = "coke", icon = nil, stage = 1, icon_size = 64},
    {item = "fawogae", iconName = "fawogae-icon", icon = nil, stage = 1, icon_size = 64},
    {item = "fawogae-substrate", icon = nil, stage = 1, icon_size = 64},
    {item = "gravel", icon = nil, stage = 1, icon_size = 64},
    {item = "ground-sample01", icon = nil, stage = 1, icon_size = 64},
    {item = "iron-oxide", icon = nil, stage = 1, icon_size = 64},
    {item = "lens", icon = nil, stage = 1, icon_size = 64},
    {item = "lime", icon = nil, stage = 1, icon_size = 64},
    {item = "limestone", icon = nil, stage = 1, icon_size = 64},
    {item = "nexelit-ore", icon = nil, stage = 1, icon_size = 64},
    {item = "nexelit-plate", icon = nil, stage = 1, icon_size = 64},
    {item = "organic-matter", iconName = "organics", icon = nil, stage = 1, icon_size = 64},
    {item = "pure-sand", icon = nil, stage = 1, icon_size = 64},
    {item = "ralesia", icon = nil, stage = 1, icon_size = 64},
    {item = "ralesia-seeds", icon = nil, stage = 1, icon_size = 64},
    {item = "raw-borax", icon = nil, stage = 1, icon_size = 64},
    {item = "rich-clay", icon = nil, stage = 1, icon_size = 64},
    {item = "sand", icon = nil, stage = 1, icon_size = 64},
    {item = "sand-casting", icon = nil, stage = 1, icon_size = 64},
    {item = "tailings-dust", icon = nil, stage = 1, icon_size = 64},
    {item = "treated-wood", icon = nil, stage = 1, icon_size = 64},
    {item = "soil", icon = nil, stage = 1, icon_size = 64},
    {item = "coarse", icon = nil, stage = 1, icon_size = 64},
    {item = "kevlar", icon = nil, stage = 2, icon_size = 64},
    {item = "nbfe-alloy", icon = nil, stage = 2, icon_size = 64},
    {item = "nichrome", icon = nil, stage = 2, icon_size = 64},
    {item = "niobium-concentrate", icon = nil, stage = 2, icon_size = 64},
    {item = "niobium-dust", icon = nil, stage = 2, icon_size = 64},
    {item = "niobium-ore", icon = nil, stage = 2, icon_size = 64},
    {item = "niobium-oxide", icon = nil, stage = 2, icon_size = 64},
    {item = "niobium-plate", icon = nil, stage = 2, icon_size = 64},
    {item = "niobium-powder", icon = nil, stage = 2, icon_size = 64},
    {item = "optical-fiber", icon = nil, stage = 2, icon_size = 64},
    {item = "fuelrod-mk01", icon = nil, stage = 3, icon_size = 64}
}
